services:
  backend:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./.byaldi/:/code/.byaldi
    restart: always

  tg_bot:
    build:
      context: ./tg_bot
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: always